package com.nextstepai.paperless.database.entity

import androidx.room.*

@Entity(tableName = "correspondents", indices = [Index(value = ["name"]), Index(value = ["ownerId", "name"], unique = true)])
data class CorrespondentEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val remoteId: String?, val ownerId: String?, val name: String, val match: String, val matchingAlgorithm: Int, val insensitive: Boolean)
@Entity(tableName = "tags", indices = [Index(value = ["name"]), Index(value = ["parentId"])])
data class TagEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val remoteId: String?, val ownerId: String?, val name: String, val match: String, val matchingAlgorithm: Int, val insensitive: Boolean, val color: String, val parentId: Long?, val isInbox: Boolean)
@Entity(tableName = "document_types", indices = [Index(value = ["name"]), Index(value = ["ownerId", "name"], unique = true)])
data class DocumentTypeEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val remoteId: String?, val ownerId: String?, val name: String, val match: String, val matchingAlgorithm: Int, val insensitive: Boolean)
@Entity(tableName = "storage_paths", indices = [Index(value = ["name"]), Index(value = ["ownerId", "name"], unique = true)])
data class StoragePathEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val remoteId: String?, val ownerId: String?, val name: String, val match: String, val matchingAlgorithm: Int, val insensitive: Boolean, val path: String)
@Entity(tableName = "documents", indices = [Index("title"), Index("created"), Index("modified"), Index("added"), Index(value = ["checksum"], unique = true), Index("archiveChecksum"), Index("pageCount"), Index("ownerId", "created"), Index("correspondentId"), Index("documentTypeId"), Index("storagePathId"), Index("rootDocumentId", "versionIndex"), Index("expiresAt")])
data class DocumentEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val remoteId: String?, val ownerId: String?, val correspondentId: Long?, val storagePathId: Long?, val title: String, val content: String, val contentLength: Long, val mimeType: String, val checksum: String, val archiveChecksum: String?, val pageCount: Int?, val created: Long, val modified: Long, val added: Long, val filename: String?, val archiveFilename: String?, val originalFilename: String?, val archiveSerialNumber: Long?, val rootDocumentId: Long?, val versionIndex: Int?, val versionLabel: String?, val documentTypeId: Long?, val expiresAt: Long?, val reminderDaysBeforeExpiry: Int?, val isDeleted: Boolean, val syncState: String, val syncedAt: Long?, val serverVersion: Long, val lastSyncedModified: Long?)
@Entity(tableName = "document_tags", primaryKeys = ["documentId", "tagId"], indices = [Index("documentId"), Index("tagId")], foreignKeys = [ForeignKey(entity = DocumentEntity::class, parentColumns = ["id"], childColumns = ["documentId"], onDelete = ForeignKey.CASCADE), ForeignKey(entity = TagEntity::class, parentColumns = ["id"], childColumns = ["tagId"], onDelete = ForeignKey.CASCADE)])
data class DocumentTagCrossRef(val documentId: Long, val tagId: Long)
@Entity(tableName = "custom_fields", indices = [Index(value = ["name"], unique = true)])
data class CustomFieldEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val name: String, val dataType: String, val extraDataJson: String?, val created: Long)
@Entity(tableName = "custom_field_instances", indices = [Index(value = ["fieldId", "valueDate"]), Index(value = ["fieldId", "valueInt"]), Index(value = ["fieldId", "valueFloat"]), Index(value = ["fieldId", "valueMonetary"]), Index(value = ["documentId", "fieldId"], unique = true)], foreignKeys = [ForeignKey(entity = DocumentEntity::class, parentColumns = ["id"], childColumns = ["documentId"], onDelete = ForeignKey.CASCADE), ForeignKey(entity = CustomFieldEntity::class, parentColumns = ["id"], childColumns = ["fieldId"], onDelete = ForeignKey.CASCADE)])
data class CustomFieldInstanceEntity(@PrimaryKey(autoGenerate = true) val id: Long = 0, val documentId: Long, val fieldId: Long, val created: Long, val valueText: String?, val valueBool: Boolean?, val valueUrl: String?, val valueDate: Long?, val valueInt: Long?, val valueFloat: Double?, val valueMonetary: String?, val valueDocumentIdsJson: String?, val valueSelect: String?, val valueLongText: String?, val isDeleted: Boolean)
